export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const FETCH_RESULTS_PENDING = "FETCH_RESULTS_PENDING";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_RESULTS_ERROR = "FETCH_RESULTS_ERROR";
export const SHOW_NEXT_RESULT_PAGE = "SHOW_NEXT_RESULT_PAGE";
export const RESULTS_PER_PAGE = 10;
